name: CI and CD Workflow for Estimation Game
on: push
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify that the deployment originates from an appropriate source
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Do code lint check
        run: npm run lint

      - name: Do code format check
        run: npm run format-check

      #- name: Run tests
      #  run: npm run test-coverage

      - name: Build production code
        run: npm run build

      - name: Setup GitHub Pages
        if: github.ref_name == 'master'
        uses: actions/configure-pages@v5

      - name: Upload production code
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy production code to GitHub Pages
        if: github.ref_name == 'master'
        id: deployment
        uses: actions/deploy-pages@v4